### PR TITLE
Avoid stubbing id for records without primary key

### LINKED ISSUE #1305: ActiveModel::MissingAttributeError when using `build_stubbed`, primary_key is not set (Rails 6)
I am trying out Rails 6 RC1. It seems that when using `build_stubbed` I get 

```
ActiveModel::MissingAttributeError:
        can't write unknown attribute ``
```

I have been looking into it and it seems that `primary_key` isn't setup on the stub instance. 

In the stub strategy in `stub_database_interaction_on_result` the ID of the stub instance is set (https://github.com/thoughtbot/factory_bot/blob/master/lib/factory_bot/strategy/stub.rb#L47), however this fails with the above Error as `@primary_key` is `nil`.

Im not sure why this issue has started to occur,  Im assuming it was due to https://github.com/rails/rails/commit/b6828fc91531ae0cc0a0f216705dd19112596301 

I guess the solution is to explicitly call `primary_key=` when doing `build_stubbed`?

factory_bot version: 5.0.2 
Rails version : 6 RC1

### PR DESCRIPTION
**Pull request by composerinteralia**
Fixes #1305

Before Rails 6 when the build_stubbed strategy assigned an id on a
record without a primary key column, the `id=` method would no-op, and
the record would end up looking like a new_record (i.e. `new_record?`
would return true because the id was nil).

This problem surfaced because of a [change in Rails 6][rails], which
caused `id=` to raise a potentially confusing
`ActiveModel::MissingAttributeError: can't write unknown attribute ''`
for records without a primary key column.

Since build_stubbed stubbed was calling `id=` for all instances,
regardless of whether they had primary keys, it was raising the above
error.

To avoid this error, we check whether the instance has a primary_key
defined before setting the id.

We also changed `persisted?` and `new_record?` to be less dependent on
the id. That way those methods will work as expected for records without
primary keys.

[rails]: https://github.com/rails/rails/commit/b6828fc91531ae0cc0a0f216705dd19112596301

### CODE REVIEW

File: lib/factory_bot/strategy/stub.rb [hunk 1]
```diff
@@ -44,15 +44,17 @@ def next_id
       end
 
       def stub_database_interaction_on_result(result_instance)
-        result_instance.id ||= next_id
+        if has_settable_id?(result_instance)
+          result_instance.id ||= next_id
```
Comment (aledustet) [inline lib/factory_bot/strategy/stub.rb]: Maybe it's not "doable" but we might want to persist the old behavior. Like assigning the ```primary_key``` the value. That way old versions would stay relevant and even if the primary key is not id it could still be set. we could do:
```ruby
result_instance.send("#{result_instance.class.primary_key}=", next_id)
``` 
Would that cover the case where the primary key is overridden to a field other than id? Or does AR aliases the method to respond to id no matter what?

File: lib/factory_bot/strategy/stub.rb [hunk 2]
```diff
@@ -44,15 +44,17 @@ def next_id
...
 
         result_instance.instance_eval do
           def persisted?
-            !new_record?
+            true
           end
 
           def new_record?
-            id.nil?
+            false
```
Comment (aledustet) [inline lib/factory_bot/strategy/stub.rb]: for completeness maybe we could do the second part of the ```has_settable_id``` method here?

File: spec/acceptance/stub_spec.rb [hunk 3]
```diff
@@ -58,3 +58,44 @@
     expect(subject.user).not_to be_new_record
   end
 end
+
+describe "a stubbed instance with no primary key" do
+  it "builds a stubbed instance" do
+    using_model_without_pk do
```
Comment (aledustet) [inline spec/acceptance/stub_spec.rb]: this definitely addresses the case without a primary key, I think my question would be: Do we even wanna support cases where the primary key is not the id field?

File: lib/factory_bot/strategy/stub.rb (hunk 2 above)
Comment (composerinteralia) [reply lib/factory_bot/strategy/stub.rb]: Do you mean `result_instance.class.primary_key`? I don't follow how that relates to this method.

File: lib/factory_bot/strategy/stub.rb (hunk 1 above)
Comment (composerinteralia) [reply lib/factory_bot/strategy/stub.rb]: I think `id=` already does the correct thing here for primary keys with a non-standard name. [Here is the relevant rails code](https://github.com/rails/rails/blob/98a57aa5f610bc66af31af409c72173cdeeb3c9e/activerecord/lib/active_record/attribute_methods/primary_key.rb#L22-L25). If we did need to change that behavior, I think it would be beyond the scope of this PR.

File: lib/factory_bot/strategy/stub.rb (hunk 2 above)
Comment (aledustet) [reply lib/factory_bot/strategy/stub.rb]: sorry, I meant the instance method primary key instead of ```id.nil?``` ```primary_key.nil?```

File: lib/factory_bot/strategy/stub.rb (hunk 1 above)
Comment (composerinteralia) [reply lib/factory_bot/strategy/stub.rb]: I tested this out and we shouldn't need any special handling of custom primary keys names in factory_bot.

File: lib/factory_bot/strategy/stub.rb (hunk 2 above)
Comment (composerinteralia) [reply lib/factory_bot/strategy/stub.rb]: `build_stubbed` objects should always act like they are `persisted?`, so I think returning `false` is OK here. Checking whether the primary_key is `nil` still wouldn't work if there is no primary key at all.
